server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vaccinationCenterDB
    password:
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      showl-sql: true
  application:
    name: VACCINATION-CENTER-SERVICE


